---
  kind: "Service"
  apiVersion: "v1"
  metadata:
    name: "template-repository"
    labels:
      id: "template-repository"
  spec:
    type: "NodePort"
    selector:
      id: "template-repository"
    ports:
      -
        port: 80
        protocol: "TCP"
        name: "rest"
